name: sport-club-manager CI workflow

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET 10.x
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '10.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run Unit Tests with Nunit and Integration Tests with Reqnroll
        run: dotnet test --no-build
      - name: Publish and Run App to Docker
        run: |
          dotnet publish --os linux --arch x64 /t:PublishContainer
          docker run --name sportclubmanager -p 5035:8080 sportclubmanager &
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Run Cypress e2e Tests
        run : |
          cd ./Tests/e2e
          npm install cypress --save-dev
          npx cypress run
