name: sport-club-manager CI workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET 10.x
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '10.x'
      - name: Display dotnet version
        run: dotnet --version
